# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "cataclysm:maledictus",
    "legendary_monsters:overgrown_colossus",
    "cataclysm:coral_golem",
    "alexsmobs:snow_leopard",
    "twilightforest:yeti",
    "alexsmobs:endergrade",
    "minecraft:horse",
    "happyghast:happy_ghast_gray",
    "rustic_engineer:dragon_fly",
    "minecraft:llama",
    "twilightforest:raven",
    "alexscaves:underzealot",
    "alexsmobs:skreecher",
    "cataclysm:ender_guardian",
    "cataclysm:deepling_warlock",
    "minecraft:tadpole",
    "aquamirae:maw",
    "alexscaves:corrodent",
    "alexsmobs:hammerhead_shark",
    "alexscaves:magnetron",
    "golem_spawn_animation:snow_golem_altar_z_java",
    "alexsmobs:grizzly_bear",
    "legendary_monsters:shulker_mimic",
    "alexsmobs:murmur_head",
    "majruszsdifficulty:cerberus",
    "goblintraders:vein_goblin_trader",
    "luminous_butterflies:spring_azure",
    "happyghast:happy_ghast_magenta",
    "minecraft:mooshroom",
    "legendary_monsters:stratling",
    "minecraft:axolotl",
    "botania:doppleganger",
    "legendary_monsters:ambusher",
    "fdbosses:chesed_monolith",
    "alexsmobs:gorilla",
    "luminous_butterflies:charaxes",
    "quark:crab",
    "alexsmobs:cosmic_cod",
    "alexscaves:deep_one_mage",
    "alexsmobs:kangaroo",
    "legendary_monsters:skeloraptor",
    "golem_spawn_animation:snow_golem_altar_jack_min_x_java",
    "alexsmobs:hummingbird",
    "happyghast:happy_ghast_yellow",
    "rustic_engineer:airship",
    "alexscaves:deep_one",
    "alexsmobs:crow",
    "rustic_engineer:wooden_cube_chest",
    "alexsmobs:guster",
    "twilightforest:minotaur",
    "luminous_butterflies:mourningcloak",
    "cataclysm:koboleton",
    "minecraft:chicken",
    "alexsmobs:giant_squid",
    "minecraft:zombie",
    "golem_spawn_animation:iron_golem_altar_x_java",
    "luminous_butterflies:buckeye",
    "alexsmobs:emu",
    "twilightforest:swarm_spider",
    "alexscaves:licowitch",
    "alexsmobs:flutter",
    "minecraft:hoglin",
    "happyghast:happy_ghast_pink",
    "twilightforest:wraith",
    "luminous_butterflies:glowstone_morpho",
    "minecraft:zombified_piglin",
    "nirvana:reefer",
    "twilightforest:snow_queen",
    "minecraft:sheep",
    "luminous_butterflies:birdwing",
    "rustic_engineer:spider_mech",
    "quark:foxhound",
    "majruszsdifficulty:giant",
    "wither_spawn_animation:animated_altar_storm_soil_x",
    "wither_spawn_animation:animated_altar_storm_soil_z",
    "twilightforest:naga",
    "alexsmobs:bone_serpent_part",
    "alexsmobs:raccoon",
    "minecraft:ravager",
    "cataclysm:clawdian",
    "alexsmobs:bone_serpent",
    "twilightforest:tiny_bird",
    "legendary_monsters:flameborn_guard",
    "cataclysm:drowned_host",
    "golem_spawn_animation:iron_golem_altarjack_z_java",
    "luminous_butterflies:yellow_swallowtail",
    "twilightforest:quest_ram",
    "alexsmobs:mudskipper",
    "alexsmobs:crimson_mosquito",
    "twilightforest:blockchain_goblin",
    "happyghast:happy_ghast_purple",
    "twilightforest:hedge_spider",
    "happyghast:happy_ghast",
    "happyghast:happy_ghast_light_blue",
    "legendary_monsters:cloud_golem",
    "alexsmobs:jerboa",
    "luminous_butterflies:hairstreak",
    "twilightforest:carminite_ghastling",
    "cataclysm:netherite_ministrosity",
    "alexsmobs:comb_jelly",
    "twilightforest:hostile_wolf",
    "golem_spawn_animation:snow_golem_altar_jack_x_java",
    "twilightforest:lower_goblin_knight",
    "alexsmobs:enderiophage",
    "alexsmobs:sunbird",
    "majruszsdifficulty:cursed_armor",
    "minecraft:cat",
    "golem_spawn_animation:snow_golem_altar_min_x_java",
    "minecraft:tropical_fish",
    "cataclysm:the_prowler",
    "alexscaves:gloomoth",
    "raidsenhanced:golem_of_last_resort",
    "alexscaves:vesper",
    "cataclysm:urchinkin",
    "alexscaves:lanternfish",
    "minecraft:zombie_villager",
    "alexsmobs:froststalker",
    "minecraft:giant",
    "alexsmobs:lobster",
    "mowziesmobs:lantern",
    "alexsmobs:seagull",
    "alexscaves:brainiac",
    "aquamirae:tortured_soul",
    "twilightforest:helmet_crab",
    "happyghast:happy_ghast_blue",
    "minecraft:husk",
    "twilightforest:redcap",
    "wither_spawn_animation:animated_altar_storm_min_z",
    "mowziesmobs:umvuthana",
    "wither_spawn_animation:animated_altar_storm_min_x",
    "twilightforest:carminite_broodling",
    "alexscaves:luxtructosaurus",
    "minecraft:donkey",
    "twilightforest:loyal_zombie",
    "mowziesmobs:umvuthana_crane_player",
    "cataclysm:the_leviathan",
    "minecraft:piglin_brute",
    "aquamirae:golden_moth",
    "twilightforest:fire_beetle",
    "golem_spawn_animation:iron_golem_altar_min_x_java",
    "twilightforest:king_spider",
    "cataclysm:the_baby_leviathan",
    "wither_spawn_animation:animated_altar_storm_x",
    "happyghast:happy_ghast_red",
    "cataclysm:deepling_brute",
    "wither_spawn_animation:animated_altar_storm_z",
    "happyghast:happy_ghast_orange",
    "alexsmobs:frilled_shark",
    "alexsmobs:bald_eagle",
    "alexsmobs:blobfish",
    "twilightforest:kobold",
    "alexscaves:gum_worm",
    "twilightforest:skeleton_druid",
    "alexsmobs:void_worm",
    "alexscaves:sweetish_fish",
    "minecraft:parrot",
    "aquamirae:spinefish",
    "cataclysm:scylla",
    "golem_spawn_animation:snow_golem_altar_jack_z_java",
    "twilightforest:adherent",
    "twilightforest:rising_zombie",
    "alexsmobs:centipede_head",
    "twilightforest:mist_wolf",
    "cataclysm:the_watcher",
    "twilightforest:ice_crystal",
    "happyghast:mount",
    "happyghast:happy_ghast_lime",
    "palegarden:creaking_heart",
    "alexsmobs:banana_slug",
    "golem_spawn_animation:snow_golem_altar_min_z_java",
    "alexsmobs:bunfungus",
    "minecraft:mule",
    "cataclysm:cindaria",
    "happyghast:ghastling",
    "ribbits:ribbit",
    "fdbosses:malkuth",
    "minecraft:vindicator",
    "luminous_butterflies:ender_eyespot",
    "alexsmobs:flying_fish",
    "majruszsdifficulty:tank",
    "twilightforest:boar",
    "quark:forgotten",
    "cataclysm:endermaptera",
    "cataclysm:lionfish",
    "cataclysm:coralssus",
    "cataclysm:the_harbinger",
    "luminous_butterflies:white_hairstreak",
    "aquamirae:luminous_jelly",
    "alexsmobs:terrapin",
    "mowziesmobs:bluff",
    "minecraft:pig",
    "alexsmobs:alligator_snapping_turtle",
    "fdbosses:judgement_bird",
    "twilightforest:winter_wolf",
    "twilightforest:unstable_ice_core",
    "twilightforest:alpha_yeti",
    "twilightforest:lich_minion",
    "minecraft:cod",
    "alexsmobs:platypus",
    "minecraft:cow",
    "alexsmobs:rocky_roller",
    "alexsmobs:soul_vulture",
    "wither_spawn_animation:animated_altar_soil_min_z",
    "alexsmobs:blue_jay",
    "minecraft:salmon",
    "cataclysm:ignis",
    "mowziesmobs:naga",
    "wither_spawn_animation:animated_altar_soil_min_x",
    "luminous_butterflies:soul_monarch",
    "alexsmobs:anteater",
    "alexsmobs:rain_frog",
    "twilightforest:plateau_boss",
    "mowziesmobs:ferrous_wroughtnaut",
    "minecraft:rabbit",
    "minecraft:pillager",
    "minecraft:zoglin",
    "alexsmobs:leafcutter_ant",
    "aquamirae:captain_cornelia",
    "cataclysm:deepling_priest",
    "legendary_monsters:skeletosaurus",
    "luminous_butterflies:monarch",
    "legendary_monsters:lava_eater",
    "twilightforest:armored_giant",
    "cataclysm:ignited_revenant",
    "alexsmobs:gazelle",
    "raidsenhanced:zapper",
    "minecraft:sniffer",
    "alexscaves:watcher",
    "mowziesmobs:umvuthana_follower_player",
    "twilightforest:penguin",
    "cataclysm:modern_remnant",
    "cataclysm:symbiocto",
    "alexsmobs:seal",
    "wither_spawn_animation:animated_altar_storm_soil_min_z",
    "alexsmobs:roadrunner",
    "alexsmobs:laviathan",
    "minecraft:trader_llama",
    "wither_spawn_animation:animated_altar_storm_soil_min_x",
    "luminous_butterflies:ringlet",
    "goblintraders:goblin_trader",
    "luminous_butterflies:zebra_longwing",
    "legendary_monsters:flameborn_warrior",
    "alexsmobs:maned_wolf",
    "minecraft:dolphin",
    "alexsmobs:gelada_monkey",
    "alexsmobs:dropbear",
    "alexsmobs:tiger",
    "legendary_monsters:haunted_knight",
    "alexscaves:caramel_cube",
    "minecraft:bee",
    "luminous_butterflies:blue_monarch",
    "alexsmobs:devils_hole_pupfish",
    "minecraft:illusioner",
    "legendary_monsters:the_obliterator",
    "happyghast:happy_ghast_brown",
    "alexsmobs:bison",
    "twilightforest:hydra",
    "mowziesmobs:foliaath",
    "mowziesmobs:frostmaw",
    "twilightforest:lich",
    "minecraft:drowned",
    "alexsmobs:tusklin",
    "alexsmobs:underminer",
    "twilightforest:snow_guardian",
    "minecraft:wandering_trader",
    "alexscaves:gumbeeper",
    "legendary_monsters:bomber",
    "luminous_butterflies:chorus_morpho",
    "cataclysm:netherite_monstrosity",
    "twilightforest:redcap_sapper",
    "cataclysm:wadjet",
    "alexscaves:boundroid",
    "mowziesmobs:umvuthana_raptor",
    "majruszsdifficulty:creeperling",
    "twilightforest:upper_goblin_knight",
    "twilightforest:knight_phantom",
    "minecraft:pufferfish",
    "trials:breeze",
    "twilightforest:dwarf_rabbit",
    "minecraft:fox",
    "luminous_butterflies:rustypage",
    "mowziesmobs:umvuthana_crane",
    "twilightforest:towerwood_borer",
    "golem_spawn_animation:iron_golem_altar_jack_min_x_java",
    "simplyswords:simplybeeentity",
    "alexsmobs:warped_toad",
    "alexsmobs:cockroach",
    "luminous_butterflies:orangetip",
    "cataclysm:elite_draugr",
    "fdbosses:geburah_bell",
    "legendary_monsters:warped_fungussus",
    "alexscaves:ferrouslime",
    "cataclysm:deepling_angler",
    "alexsmobs:capuchin_monkey",
    "luminous_butterflies:little_wood",
    "cataclysm:draugr",
    "minecraft:polar_bear",
    "minecraft:turtle",
    "quark:wraith",
    "alexsmobs:rattlesnake",
    "legendary_monsters:frostbitten_golem",
    "rustic_engineer:submarine_abyssal",
    "alexsmobs:potoo",
    "alexsmobs:fly",
    "alexscaves:trilocaris",
    "quark:shiba",
    "mowziesmobs:elokosa_follower_howler",
    "luminous_butterflies:black_swallowtail",
    "alexsmobs:straddler",
    "alexsmobs:sea_bear",
    "alexscaves:nucleeper",
    "alexscaves:hullbreaker",
    "mowziesmobs:umvuthana_follower_raptor",
    "cataclysm:ender_golem",
    "alexsmobs:sugar_glider",
    "happyghast:happy_ghast_white",
    "supplementaries:red_merchant",
    "luminous_butterflies:crimson_monarch",
    "aquamirae:eel",
    "golem_spawn_animation:iron_golem_altar_jack_x_java",
    "alexsmobs:orca",
    "twilightforest:bighorn_sheep",
    "twilightforest:stable_ice_core",
    "minecraft:bat",
    "alexsmobs:cosmaw",
    "legendary_monsters:knights_armor",
    "luminous_butterflies:cherryrose",
    "wither_spawn_animation:animated_altar_bygone_z",
    "wither_spawn_animation:animated_altar_bygone_x",
    "legendary_monsters:withered_abomination",
    "alexsmobs:skunk",
    "aquamirae:anglerfish",
    "legendary_monsters:annihilation_pursuer",
    "cataclysm:deepling",
    "alexsmobs:tasmanian_devil",
    "cataclysm:ancient_remnant",
    "alexsmobs:stradpole",
    "minecraft:panda",
    "legendary_monsters:wandering_eye",
    "twilightforest:harbinger_cube",
    "alexsmobs:moose",
    "golem_spawn_animation:snow_golem_altar_x_java",
    "alexsmobs:shoebill",
    "alexsmobs:farseer",
    "cataclysm:amethyst_crab",
    "legendary_monsters:mossy_golem",
    "mowziesmobs:elokosa_howler",
    "alexsmobs:warped_mosco",
    "legendary_monsters:haunted_guard",
    "twilightforest:ur_ghast",
    "alexsmobs:komodo_dragon",
    "alexscaves:forsaken",
    "aquamirae:maze_mother",
    "alexscaves:mine_guardian",
    "cataclysm:ignited_berserker",
    "quark:stoneling",
    "legendary_monsters:flame_drifter",
    "alexsmobs:crocodile",
    "alexscaves:teletor",
    "quark:toretoise",
    "majruszsdifficulty:illusioner",
    "fdbosses:fire_malkuth_warrior",
    "alexsmobs:triops",
    "alexsmobs:rhinoceros",
    "alexsmobs:mimicube",
    "raidsenhanced:raid_drill",
    "twilightforest:slime_beetle",
    "twilightforest:pinch_beetle",
    "alexscaves:gingerbread_man",
    "minecraft:frog",
    "twilightforest:deer",
    "legendary_monsters:guard",
    "alexsmobs:mimic_octopus",
    "alexsmobs:void_worm_part",
    "twilightforest:minoshroom",
    "twilightforest:squirrel",
    "alexscaves:caniac",
    "aquamirae:pillagers_patrol",
    "twilightforest:carminite_ghastguard",
    "minecraft:evoker",
    "alexsmobs:tarantula_hawk",
    "alexsmobs:cachalot_whale",
    "twilightforest:roving_cube",
    "rustic_engineer:wooden_cube",
    "legendary_monsters:spiky_bug",
    "alexscaves:gammaroach",
    "wither_spawn_animation:animated_altar_soil_z",
    "wither_spawn_animation:animated_altar_soil_x",
    "cataclysm:hippocamtus",
    "alexscaves:notor",
    "fdbosses:chesed",
    "golem_spawn_animation:iron_golem_altar_z_java",
    "wither_spawn_animation:animated_altar_x",
    "alexsmobs:anaconda",
    "wither_spawn_animation:animated_altar_z",
    "mowziesmobs:grottol",
    "legendary_monsters:hovering_hurricane",
    "legendary_monsters:dune_sentinel",
    "mowziesmobs:baby_foliaath",
    "minecraft:goat",
    "twilightforest:death_tome",
    "palegarden:creaking",
    "alexsmobs:mantis_shrimp",
    "legendary_monsters:posessed_paladin",
    "mowziesmobs:umvuthi",
    "alexscaves:radgill",
    "golem_spawn_animation:iron_golem_altar_jack_min_z_java",
    "happyghast:happy_ghast_green",
    "alexsmobs:toucan",
    "happyghast:happy_ghast_cyan",
    "twilightforest:mosquito_swarm",
    "wither_spawn_animation:animated_altar_min_x",
    "wither_spawn_animation:animated_altar_min_z",
    "alexsmobs:murmur",
    "raidsenhanced:raid_blimp",
    "legendary_monsters:chorusling",
    "golem_spawn_animation:snow_golem_altar_jack_min_z_java",
    "legendary_monsters:ancient_guardian",
    "trials:bogged",
    "alexsmobs:mungus",
    "alexsmobs:caiman",
    "alexsmobs:spectre",
    "cataclysm:kobolediator",
    "twilightforest:troll",
    "twilightforest:carminite_golem",
    "alexsmobs:catfish",
    "happyghast:happy_ghast_black",
    "wither_spawn_animation:animated_altar_bygone_min_x",
    "minecraft:piglin",
    "wither_spawn_animation:animated_altar_bygone_min_z",
    "alexsmobs:skelewag",
    "alexscaves:boundroid_winch",
    "alexscaves:deep_one_knight",
    "alexsmobs:elephant",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "luminous_butterflies:emerald_swallowtail",
    "cataclysm:royal_draugr",
    "twilightforest:maze_slime",
    "legendary_monsters:endersent",
    "twilightforest:giant_miner",
    "cataclysm:aptrgangr",
    "fdbosses:ice_malkuth_warrior",
    "minecraft:ocelot",
    "golem_spawn_animation:iron_golem_altar_min_z_java",
    "minecraft:wolf"
]
